//USER REDUCER TYPES
export const SET_AUTHENTICATED = "[user] SET_AUTHENTICATED"
export const SET_UNAUTHENTICATED = "[user] SET_UNAUTHENTICATED"
export const SET_USER = "[user] SET_USER"
export const LOADING_USER = "[user] LOADING_USER"

//UI REDUCER TYPES
export const SET_ERRORS = "[ui] SET_ERRORS"
export const LOADING_UI = "[ui] LOADING_UI"
export const CLEAR_ERRORS = "[ui] CLEAR_ERRORS"


//  DATA REDUCER TYPES
export const PRODUCT_LIST_REQUEST = "[product] PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "[product] PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL = "[product] PRODUCT_LIST_FAIL"
export const PRODUCT_LIST_LOADING = "[product] PRODUCT_LIST_LOADING"

export const PRODUCT_DETAILS_REQUEST = "[product details] PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "[product details] PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_LOADING = "[product details] PRODUCT_DETAILS_LOADING"
export const PRODUCT_DETAILS_FAIL = "[product details] PRODUCT_DETAILS_FAIL"


//SIDEBAR TOGGLED
export const SHOW_SIDEBAR = "[sidebar] SHOW_SIDEBAR"